ALTER TABLE `spell_dbc`
DROP COLUMN `EffectBaseDice1`;
ALTER TABLE `spell_dbc`
DROP COLUMN `EffectBaseDice2`;
ALTER TABLE `spell_dbc`
DROP COLUMN `EffectBaseDice3`;
ALTER TABLE `spell_dbc`
DROP COLUMN `EffectDicePerLevel1`;
ALTER TABLE `spell_dbc`
DROP COLUMN `EffectDicePerLevel2`;
ALTER TABLE `spell_dbc`
DROP COLUMN `EffectDicePerLevel3`;